const SITE = 'https://alastromoody.github.io';

export const projects = [
  {
    id: 'poe',
    title: 'POE Timeless Jewels',
    shortTitle: 'POE',
    url: `${SITE}/poe/`,
    description: 'Калькулятор вневременных самоцветов для Path of Exile 1. Расчёты на WASM, интерактивное дерево умений на canvas.',
    tags: ['WASM', 'Canvas', 'POE'],
    theme: 'poe',
    orbit: 'inner',
    angle: 0,
  },
  {
    id: 'radio',
    title: 'Radio',
    shortTitle: 'Radio',
    url: `${SITE}/radio/`,
    description: 'Онлайн-радио, удобное прослушивание аудиокниг и доступ к музыке YouTube. PWA.',
    tags: ['PWA', 'Audio'],
    theme: 'radio',
    orbit: 'inner',
    angle: 120,
  },
  {
    id: 'weather',
    title: 'Weather',
    shortTitle: 'Weather',
    url: `${SITE}/weather/`,
    description: 'Погода с красивой WebGL-анимацией. PWA.',
    tags: ['WebGL', 'PWA'],
    theme: 'weather',
    orbit: 'inner',
    angle: 240,
    rings: true,
  },
  {
    id: 'budget',
    title: 'Budget',
    shortTitle: 'Budget',
    url: `${SITE}/budget/`,
    description: 'Контроль финансов: загрузка выписок из банковских приложений, категории и таблицы. Local-first, PWA.',
    tags: ['PWA', 'Local-first'],
    theme: 'budget',
    orbit: 'outer',
    angle: 30,
  },
  {
    id: 'gs',
    title: 'Goblin Survival',
    shortTitle: 'GS',
    url: `${SITE}/gs/`,
    description: 'Интерактивный редактор персонажа, дерево крафта и библиотека оружия для карты Warcraft 3 — Goblin Survival.',
    tags: ['WC3', 'Craft'],
    theme: 'gs',
    orbit: 'outer',
    angle: 102,
  },
  {
    id: 'pwa-magic',
    title: 'PWA Magic',
    shortTitle: 'PWA Magic',
    url: `${SITE}/pwa-magic/`,
    description: 'Примеры работы с разными Web API.',
    tags: ['Web API', 'PWA'],
    theme: 'pwa-magic',
    orbit: 'outer',
    angle: 174,
  },
  {
    id: 'tcom',
    title: 'TCOM',
    shortTitle: 'TCOM',
    url: `${SITE}/tcom/`,
    description: 'Каталог предметов для одноимённой карты Warcraft 3.',
    tags: ['WC3', 'Catalog'],
    theme: 'tcom',
    orbit: 'outer',
    angle: 246,
  },
];
